apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2-zone-aware
  labels:
    app: a2-zone-aware
spec:
  replicas: 10
  selector:
    matchLabels:
      app: a2-zone-aware
  template:
    metadata:
      labels:
        app: a2-zone-aware
    spec:
      containers:
        - name: a2-zone-aware
          image: yanchenglee/taska1
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3000
          resources:
            limits:
              cpu: 40m
              memory: 100Mi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: a2-zone-aware